 SELECT
	'REF_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN REF_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN REF_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'DIRECTION' AS COLUMN_NAME,
	COUNT(CASE WHEN DIRECTION IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN DIRECTION IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'MSG_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN MSG_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN MSG_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'TRAN_DATE' AS COLUMN_NAME,
	COUNT(CASE WHEN TRAN_DATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN TRAN_DATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'COPY_FLAG' AS COLUMN_NAME,
	COUNT(CASE WHEN COPY_FLAG IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN COPY_FLAG IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'DPLCT_FLAG' AS COLUMN_NAME,
	COUNT(CASE WHEN DPLCT_FLAG IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN DPLCT_FLAG IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SEND_BANK_MMB_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN SEND_BANK_MMB_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SEND_BANK_MMB_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SEND_BANK_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN SEND_BANK_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SEND_BANK_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SEND_BANK_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN SEND_BANK_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SEND_BANK_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'RCV_BANK_MMB_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN RCV_BANK_MMB_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RCV_BANK_MMB_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'RCV_BANK_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN RCV_BANK_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RCV_BANK_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SETTLE_METHOD' AS COLUMN_NAME,
	COUNT(CASE WHEN SETTLE_METHOD IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SETTLE_METHOD IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SETTLE_ACCT' AS COLUMN_NAME,
	COUNT(CASE WHEN SETTLE_ACCT IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SETTLE_ACCT IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SETTLE_ACCT_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN SETTLE_ACCT_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SETTLE_ACCT_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SEND_AGENT_MMB_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN SEND_AGENT_MMB_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SEND_AGENT_MMB_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SEND_AGENT_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN SEND_AGENT_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SEND_AGENT_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SEND_AGENT_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN SEND_AGENT_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SEND_AGENT_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SEND_AGENT_COUNTRY' AS COLUMN_NAME,
	COUNT(CASE WHEN SEND_AGENT_COUNTRY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SEND_AGENT_COUNTRY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SEND_AGENT_CITY_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN SEND_AGENT_CITY_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SEND_AGENT_CITY_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'RCV_AGENT_MMB_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN RCV_AGENT_MMB_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RCV_AGENT_MMB_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'RCV_AGENT_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN RCV_AGENT_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RCV_AGENT_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'RCV_AGENT_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN RCV_AGENT_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RCV_AGENT_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'RCV_AGENT_COUNTRY' AS COLUMN_NAME,
	COUNT(CASE WHEN RCV_AGENT_COUNTRY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RCV_AGENT_COUNTRY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'RCV_AGENT_CITY_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN RCV_AGENT_CITY_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RCV_AGENT_CITY_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'THIRD_AGENT_MMB_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN THIRD_AGENT_MMB_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN THIRD_AGENT_MMB_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'THIRD_AGENT_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN THIRD_AGENT_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN THIRD_AGENT_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'THIRD_AGENT_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN THIRD_AGENT_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN THIRD_AGENT_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'THIRD_AGENT_COUNTRY' AS COLUMN_NAME,
	COUNT(CASE WHEN THIRD_AGENT_COUNTRY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN THIRD_AGENT_COUNTRY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'THIRD_AGENT_CITY_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN THIRD_AGENT_CITY_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN THIRD_AGENT_CITY_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'CLEAR_SYSTEM_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN CLEAR_SYSTEM_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN CLEAR_SYSTEM_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INSTRUCTED_AMT' AS COLUMN_NAME,
	COUNT(CASE WHEN INSTRUCTED_AMT IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INSTRUCTED_AMT IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INSTRUCTED_CCY' AS COLUMN_NAME,
	COUNT(CASE WHEN INSTRUCTED_CCY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INSTRUCTED_CCY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_MMB_ID1' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_MMB_ID1 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_MMB_ID1 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_MMB_ID2' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_MMB_ID2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_MMB_ID2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_CODE2' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_CODE2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_CODE2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_NAME2' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_NAME2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_NAME2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_COUNTRY2' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_COUNTRY2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_COUNTRY2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_CITY_NAME2' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_CITY_NAME2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_CITY_NAME2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_MMB_ID3' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_MMB_ID3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_MMB_ID3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_CODE3' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_CODE3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_CODE3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_NAME3' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_NAME3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_NAME3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_COUNTRY3' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_COUNTRY3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_COUNTRY3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRVS_BANK_CITY_NAME3' AS COLUMN_NAME,
	COUNT(CASE WHEN PRVS_BANK_CITY_NAME3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRVS_BANK_CITY_NAME3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_MMB_ID1' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_MMB_ID1 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_MMB_ID1 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_NAME1' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_NAME1 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_NAME1 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_CITY_NAME1' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_CITY_NAME1 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_CITY_NAME1 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_COUNTRY1' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_COUNTRY1 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_COUNTRY1 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_MMB_ID2' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_MMB_ID2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_MMB_ID2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_NAME2' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_NAME2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_NAME2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_CITY_NAME2' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_CITY_NAME2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_CITY_NAME2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_COUNTRY2' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_COUNTRY2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_COUNTRY2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_MMB_ID3' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_MMB_ID3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_MMB_ID3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_NAME3' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_NAME3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_NAME3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_CITY_NAME3' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_CITY_NAME3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_CITY_NAME3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'INTR_BANK_COUNTRY3' AS COLUMN_NAME,
	COUNT(CASE WHEN INTR_BANK_COUNTRY3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN INTR_BANK_COUNTRY3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'FINAL_PAYER_CITY_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN FINAL_PAYER_CITY_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN FINAL_PAYER_CITY_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'FINAL_PAYER_COUNTRY' AS COLUMN_NAME,
	COUNT(CASE WHEN FINAL_PAYER_COUNTRY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN FINAL_PAYER_COUNTRY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'FINAL_PAYER_BANK' AS COLUMN_NAME,
	COUNT(CASE WHEN FINAL_PAYER_BANK IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN FINAL_PAYER_BANK IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_SEND_BANK_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_SEND_BANK_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_SEND_BANK_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_SEND_BANK_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_SEND_BANK_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_SEND_BANK_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_SEND_BANK_CITY' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_SEND_BANK_CITY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_SEND_BANK_CITY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_SEND_BANK_COUNTRY' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_SEND_BANK_COUNTRY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_SEND_BANK_COUNTRY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_BANK_MMB_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_BANK_MMB_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_BANK_MMB_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_BANK_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_BANK_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_BANK_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_BANK_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_BANK_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_BANK_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_ADDR_LINE1' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_ADDR_LINE1 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_ADDR_LINE1 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_ADDR_LINE2' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_ADDR_LINE2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_ADDR_LINE2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_ADDR_LINE3' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_ADDR_LINE3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_ADDR_LINE3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYER_OPEN_MMB_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYER_OPEN_MMB_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYER_OPEN_MMB_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_OPEN_MMB_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_OPEN_MMB_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_OPEN_MMB_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_OPEN_BRANCH' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_OPEN_BRANCH IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_OPEN_BRANCH IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_BANK_MMB_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_BANK_MMB_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_BANK_MMB_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_BANK_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_BANK_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_BANK_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_ADDR_LINE1' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_ADDR_LINE1 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_ADDR_LINE1 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_ADDR_LINE2' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_ADDR_LINE2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_ADDR_LINE2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_ADDR_LINE3' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_ADDR_LINE3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_ADDR_LINE3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'FINAL_PAYEE_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN FINAL_PAYEE_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN FINAL_PAYEE_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'FINAL_PAYEE_CITY_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN FINAL_PAYEE_CITY_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN FINAL_PAYEE_CITY_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'FINAL_PAYEE_COUNTRY' AS COLUMN_NAME,
	COUNT(CASE WHEN FINAL_PAYEE_COUNTRY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN FINAL_PAYEE_COUNTRY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'FINAL_PAYEE_BANK' AS COLUMN_NAME,
	COUNT(CASE WHEN FINAL_PAYEE_BANK IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN FINAL_PAYEE_BANK IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'FEE_AMT' AS COLUMN_NAME,
	COUNT(CASE WHEN FEE_AMT IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN FEE_AMT IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'CANCEL_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN CANCEL_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN CANCEL_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'IS_ENTRUSTED_PAYMENT' AS COLUMN_NAME,
	COUNT(CASE WHEN IS_ENTRUSTED_PAYMENT IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN IS_ENTRUSTED_PAYMENT IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'IOU_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN IOU_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN IOU_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'HANG_SEQ_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN HANG_SEQ_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN HANG_SEQ_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'IS_PERSON' AS COLUMN_NAME,
	COUNT(CASE WHEN IS_PERSON IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN IS_PERSON IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAPER_INSTRUCTIONS' AS COLUMN_NAME,
	COUNT(CASE WHEN PAPER_INSTRUCTIONS IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAPER_INSTRUCTIONS IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'DEBIT_AMT' AS COLUMN_NAME,
	COUNT(CASE WHEN DEBIT_AMT IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN DEBIT_AMT IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'CREDIT_AMT' AS COLUMN_NAME,
	COUNT(CASE WHEN CREDIT_AMT IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN CREDIT_AMT IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'USA_AMT' AS COLUMN_NAME,
	COUNT(CASE WHEN USA_AMT IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN USA_AMT IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'COST_CENTER' AS COLUMN_NAME,
	COUNT(CASE WHEN COST_CENTER IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN COST_CENTER IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_INSTITUTION_COUNTRY' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_INSTITUTION_COUNTRY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_INSTITUTION_COUNTRY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'IS_CORPORATE' AS COLUMN_NAME,
	COUNT(CASE WHEN IS_CORPORATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN IS_CORPORATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SETTLE_ACCT_NAME' AS COLUMN_NAME,
	COUNT(CASE WHEN SETTLE_ACCT_NAME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SETTLE_ACCT_NAME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PTP_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN PTP_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PTP_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'CLIENT_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN CLIENT_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN CLIENT_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'VALUE_DATE' AS COLUMN_NAME,
	COUNT(CASE WHEN VALUE_DATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN VALUE_DATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'MSG_SEND_TIME' AS COLUMN_NAME,
	COUNT(CASE WHEN MSG_SEND_TIME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN MSG_SEND_TIME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PRE_CHARGE' AS COLUMN_NAME,
	COUNT(CASE WHEN PRE_CHARGE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRE_CHARGE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'OPERATOR_TIME_STAMP' AS COLUMN_NAME,
	COUNT(CASE WHEN OPERATOR_TIME_STAMP IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN OPERATOR_TIME_STAMP IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'EFFECT_DATE' AS COLUMN_NAME,
	COUNT(CASE WHEN EFFECT_DATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN EFFECT_DATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'BUY_RATE' AS COLUMN_NAME,
	COUNT(CASE WHEN BUY_RATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN BUY_RATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'SELL_RATE' AS COLUMN_NAME,
	COUNT(CASE WHEN SELL_RATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SELL_RATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'FLOAT_RATE' AS COLUMN_NAME,
	COUNT(CASE WHEN FLOAT_RATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN FLOAT_RATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'DEBIT_ACCT_SEQ' AS COLUMN_NAME,
	COUNT(CASE WHEN DEBIT_ACCT_SEQ IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN DEBIT_ACCT_SEQ IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'CREDIT_ACCT_SEQ' AS COLUMN_NAME,
	COUNT(CASE WHEN CREDIT_ACCT_SEQ IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN CREDIT_ACCT_SEQ IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'CREDIT_CLIENT_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN CREDIT_CLIENT_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN CREDIT_CLIENT_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'OPTION_TYPE' AS COLUMN_NAME,
	COUNT(CASE WHEN OPTION_TYPE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN OPTION_TYPE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_OPEN_BANK_RMT_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_OPEN_BANK_RMT_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_OPEN_BANK_RMT_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_OPEN_BANK_POSTSCRIPT' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_OPEN_BANK_POSTSCRIPT IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_OPEN_BANK_POSTSCRIPT IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_OPEN_BANK_RMT_CODE2' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_OPEN_BANK_RMT_CODE2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_OPEN_BANK_RMT_CODE2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PAYEE_OPEN_BANK_POSTSCRIPT2' AS COLUMN_NAME,
	COUNT(CASE WHEN PAYEE_OPEN_BANK_POSTSCRIPT2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PAYEE_OPEN_BANK_POSTSCRIPT2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'AGENT_BANK_POSTSCRIPT' AS COLUMN_NAME,
	COUNT(CASE WHEN AGENT_BANK_POSTSCRIPT IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN AGENT_BANK_POSTSCRIPT IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'PURPOSE_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN PURPOSE_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PURPOSE_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
UNION ALL
 SELECT
	'TRAN_REF_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN TRAN_REF_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN TRAN_REF_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_cbpc_credit_payment
;
