 SELECT
	'REF_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN REF_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN REF_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'SOURCE_REFERENCE' AS COLUMN_NAME,
	COUNT(CASE WHEN SOURCE_REFERENCE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SOURCE_REFERENCE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'SOURCE_DATE' AS COLUMN_NAME,
	COUNT(CASE WHEN SOURCE_DATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SOURCE_DATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'TRAN_DATE' AS COLUMN_NAME,
	COUNT(CASE WHEN TRAN_DATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN TRAN_DATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'SETTLE_DATE' AS COLUMN_NAME,
	COUNT(CASE WHEN SETTLE_DATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SETTLE_DATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'TRAN_TIME_STAMP' AS COLUMN_NAME,
	COUNT(CASE WHEN TRAN_TIME_STAMP IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN TRAN_TIME_STAMP IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'USER_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN USER_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN USER_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'RE_USER_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN RE_USER_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RE_USER_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'ORIG_REF_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN ORIG_REF_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN ORIG_REF_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'BUSI_REF_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN BUSI_REF_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN BUSI_REF_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'RELATED_REF_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN RELATED_REF_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RELATED_REF_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'DIRECTION' AS COLUMN_NAME,
	COUNT(CASE WHEN DIRECTION IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN DIRECTION IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'MSG_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN MSG_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN MSG_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'CCY' AS COLUMN_NAME,
	COUNT(CASE WHEN CCY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN CCY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'TRAN_AMT' AS COLUMN_NAME,
	COUNT(CASE WHEN TRAN_AMT IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN TRAN_AMT IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'SEND_BANK_NODE' AS COLUMN_NAME,
	COUNT(CASE WHEN SEND_BANK_NODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SEND_BANK_NODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'CORE_REF_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN CORE_REF_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN CORE_REF_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'CORE_TRAN_DATE' AS COLUMN_NAME,
	COUNT(CASE WHEN CORE_TRAN_DATE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN CORE_TRAN_DATE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'TRUSTED_PAY_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN TRUSTED_PAY_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN TRUSTED_PAY_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'BUSI_TYPE' AS COLUMN_NAME,
	COUNT(CASE WHEN BUSI_TYPE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN BUSI_TYPE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'TRAN_CATEGORY' AS COLUMN_NAME,
	COUNT(CASE WHEN TRAN_CATEGORY IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN TRAN_CATEGORY IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'EXCEPTION_REASON' AS COLUMN_NAME,
	COUNT(CASE WHEN EXCEPTION_REASON IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN EXCEPTION_REASON IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'SYSTEM_ID' AS COLUMN_NAME,
	COUNT(CASE WHEN SYSTEM_ID IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN SYSTEM_ID IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'PRINT_TIME' AS COLUMN_NAME,
	COUNT(CASE WHEN PRINT_TIME IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PRINT_TIME IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'DEST_MODULE' AS COLUMN_NAME,
	COUNT(CASE WHEN DEST_MODULE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN DEST_MODULE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'BUSI_STATUS' AS COLUMN_NAME,
	COUNT(CASE WHEN BUSI_STATUS IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN BUSI_STATUS IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'ORIG_STATUS' AS COLUMN_NAME,
	COUNT(CASE WHEN ORIG_STATUS IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN ORIG_STATUS IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'RESPONSE_CODE' AS COLUMN_NAME,
	COUNT(CASE WHEN RESPONSE_CODE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RESPONSE_CODE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'RESPONSE_MESSAGE' AS COLUMN_NAME,
	COUNT(CASE WHEN RESPONSE_MESSAGE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN RESPONSE_MESSAGE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'LAST_UPD_TIMESTAMP' AS COLUMN_NAME,
	COUNT(CASE WHEN LAST_UPD_TIMESTAMP IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN LAST_UPD_TIMESTAMP IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'ACCT_STATUS' AS COLUMN_NAME,
	COUNT(CASE WHEN ACCT_STATUS IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN ACCT_STATUS IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'PURPOSE' AS COLUMN_NAME,
	COUNT(CASE WHEN PURPOSE IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PURPOSE IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'PCS_BUSI1' AS COLUMN_NAME,
	COUNT(CASE WHEN PCS_BUSI1 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PCS_BUSI1 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'PCS_BUSI2' AS COLUMN_NAME,
	COUNT(CASE WHEN PCS_BUSI2 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PCS_BUSI2 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'PCS_BUSI3' AS COLUMN_NAME,
	COUNT(CASE WHEN PCS_BUSI3 IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PCS_BUSI3 IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'TRAN_STATUS' AS COLUMN_NAME,
	COUNT(CASE WHEN TRAN_STATUS IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN TRAN_STATUS IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'UETR' AS COLUMN_NAME,
	COUNT(CASE WHEN UETR IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN UETR IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'BUS_BELONGS_DEP' AS COLUMN_NAME,
	COUNT(CASE WHEN BUS_BELONGS_DEP IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN BUS_BELONGS_DEP IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'PROCESS_REASON' AS COLUMN_NAME,
	COUNT(CASE WHEN PROCESS_REASON IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN PROCESS_REASON IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
UNION ALL
 SELECT
	'BATCH_NO' AS COLUMN_NAME,
	COUNT(CASE WHEN BATCH_NO IS NULL THEN 1 END) AS IS_NULL,
	COUNT(CASE WHEN BATCH_NO IS NOT NULL THEN 1 END) AS IS_NOT_NULL
FROM pt_tran_msg
;
